### ISSUE TITLE
Make a Readme

### ISSUE THREAD

**Issue by fortepc** [TrainerDex/The-CP-Game#2]

**Comment by TurnrDev** [comment]
Create a PR and I'll happily accept it.

**Comment by fortepc** [comment]
I haven't been able to use the bot to be able to know what to write in a readme xD

**Comment by fortepc** [comment]
but also it died. sadness.

**Comment by TurnrDev** [comment]
Yeah, the OCR never worked. It should have worked. I just couldn't figure out why it wasn't working. Probably the same bug plaguing the main bot with iPhone screenshots. Didn't care enough to fix it.
